values = {
    'index_column': "PassengerId",
    'target_column': "Survived",
    'fold_type': 'kfold',  # None, stratified, kfold
    'n_fold': 7,

    'original_data_path': "data/original/",
    'output_data_path': "data/output/",
    'transformed_data_path': "data/transformed/",
    'models_data_path': "data/models/",
    'test_file': "test.csv",
    'train_file': "train.csv",

    # 'main_transformations': [
    #     # ["Pclass",          ["drop_column"]],
    #     ["Name",            ["drop_column"]],
    #     ["Sex",                 ["numeric_categories"]],
    #     ["Pclass",                 ["numeric_categories"]],
    #     # ["Age",         ["drop_column"]],
    #     ["SibSp",           ["drop_column"]],
    #     ["Parch",           ["drop_column"]],
    #     ["Ticket",          ["drop_column"]],
    #     ["Fare",            ["drop_column"]],
    #     ["Cabin",           ["drop_column"]],
    #     ["Embarked",            ["drop_column"]],
    #     ["Age",                 ["nan_mean_from_columns", ['Sex', 'Pclass']]],
    #     ["Age",                 ["split_by_defined", [0, 9, 15, 20, 25, 31, 40, 50, 60, 90]]],
    #     ["Age",                 ["numeric_categories"]],
    #     ["Age",                 ["one_hot"]],
    #     ["Sex",         ["one_hot"]],
    #     ["Pclass",         ["one_hot"]],
    # ]
    'main_transformations': [
        # ["CabinBool",           ["copy_column", "Cabin"]],
        ["Title",               ["copy_column", "Name"]],
        ["Name",       	        ["string_length"]],
        ["FamilySize",          ["add_columns", "Parch", "SibSp"]],
        ["Parch",      	        ["drop_column"]],
        ["SibSp",      	        ["drop_column"]],

        # ["CabinBool",           ["nan_boolean"]],
        ["Fare",                ["nan_mean"]],
        ["Embarked",            ["nan_static", 'S']],

        ["Cabin",               ["first_character"]],

        ["IsAlone",             ["extract_dummy", "FamilySize", '==', 0]],
        # ["LargeFamily",         ["extract_dummy", "FamilySize", '>', 4]],
        ["TicketFrequency",     ["count_fequencies", "Ticket"]],
        ["Ticket",              ["duplicate_dummies"]],
        ["Fare",                ["split_by_qcut", 4]],
        ["FamilySize",          ["split_by_cut", 4]],

        ["Title",               ["regex_extract", " ([A-Za-z]+)\."]],
        ["Title",               ["str_replace", ['Lady', 'Countess', 'Dona'], 'Royalty']],
        ["Title",               ["str_replace", ['Capt', 'Col', 'Major', 'Rev'], 'Officer']],
        ["Title",               ["str_replace", ['Jonkheer', 'Don', 'Sir'], 'Royalty']],
        ["Title",               ["str_replace", ['Mlle', 'Ms'], 'Miss']],
        ["Title",               ["str_replace", 'Mme', 'Mrs']],

        ["Sex",                 ["numeric_categories"]],
        ["Age",                 ["nan_mean_from_columns", ['Sex', 'Pclass', 'Title']]],
        ["Age",                 ["split_by_defined", [0, 9, 15, 20, 25, 31, 40, 50, 60, 90]]],
        ["Age",                 ["numeric_categories"]],
        ["Fare",                ["numeric_categories"]],
        ["FamilySize",          ["numeric_categories"]],

        ["Age",                 ["one_hot"]],
        ["Cabin",               ["one_hot"]],
        ["Embarked",            ["one_hot"]],
        ["Fare",                ["one_hot"]],
        ["FamilySize",          ["one_hot"]],
        ["Name",                ["one_hot"]],
        ["Title",               ["one_hot"]],
        ["TicketFrequency",     ["one_hot"]],
        ["Pclass",              ["one_hot"]],
        ["Sex",                 ["one_hot"]],

        ["Ticket_137",          ["drop_column"]],
        ["Ticket_114",          ["drop_column"]],
        ["Ticket_110",          ["drop_column"]],
        ["Ticket_109",          ["drop_column"]],
        ["Ticket_141",          ["drop_column"]],
        ["Ticket_74",           ["drop_column"]],
        ["Name_41",             ["drop_column"]],
        ["Ticket_50",           ["drop_column"]],
        ["Ticket_49",           ["drop_column"]],
        ["Ticket_45",           ["drop_column"]],
        ["Ticket_43",           ["drop_column"]],
        ["Cabin_F",             ["drop_column"]],
        ["Ticket_41",           ["drop_column"]],
        ["Ticket_38",           ["drop_column"]],
        ["Ticket_35",           ["drop_column"]],
        ["Ticket_34",           ["drop_column"]],
        ["Ticket_33",           ["drop_column"]],
        ["Ticket_29",           ["drop_column"]],
        ["Ticket_28",           ["drop_column"]],
        ["Name_35",             ["drop_column"]],
        ["Ticket_27",           ["drop_column"]],
        ["Name_43",             ["drop_column"]],
        ["Ticket_76",           ["drop_column"]],
        ["Name_44",             ["drop_column"]],
        ["Name_45",             ["drop_column"]],
        ["Ticket_24",           ["drop_column"]],
        ["Name_48",             ["drop_column"]],
        ["Name_49",             ["drop_column"]],
        ["Name_50",             ["drop_column"]],
        ["Name_51",             ["drop_column"]],
        ["Name_52",             ["drop_column"]],
        ["Name_53",             ["drop_column"]],
        ["Ticket_21",           ["drop_column"]],
        ["Ticket_19",           ["drop_column"]],
        ["Ticket_11",           ["drop_column"]],
        ["Ticket_10",           ["drop_column"]],
        ["Ticket_8",            ["drop_column"]],
        ["Ticket_51",           ["drop_column"]],
        ["Ticket_197",          ["drop_column"]],
        ["Ticket_190",          ["drop_column"]],
        ["Ticket_187",          ["drop_column"]],
        ["Ticket_79",           ["drop_column"]],
        ["Ticket_80",           ["drop_column"]],
        ["Ticket_90",           ["drop_column"]],
        ["Ticket_93",           ["drop_column"]],
        ["Ticket_97",           ["drop_column"]],
        ["Ticket_73",           ["drop_column"]],
        ["Ticket_71",           ["drop_column"]],
        ["Ticket_66",           ["drop_column"]],
        ["Ticket_111",          ["drop_column"]],
        ["Ticket_64",           ["drop_column"]],
        ["Ticket_122",          ["drop_column"]],
        ["Ticket_125",          ["drop_column"]],
        ["Ticket_126",          ["drop_column"]],
        ["Ticket_127",          ["drop_column"]],
        ["Ticket_128",          ["drop_column"]],
        ["Ticket_63",           ["drop_column"]],
        ["Ticket_140",          ["drop_column"]],
        ["Ticket_4",            ["drop_column"]],
        ["Ticket_155",          ["drop_column"]],
        ["Ticket_57",           ["drop_column"]],
        ["Ticket_158",          ["drop_column"]],
        ["Ticket_164",          ["drop_column"]],
        ["Ticket_166",          ["drop_column"]],
        ["Ticket_168",          ["drop_column"]],
        ["Ticket_169",          ["drop_column"]],
        ["Ticket_178",          ["drop_column"]],
        ["Ticket_179",          ["drop_column"]],
        ["Ticket_180",          ["drop_column"]],
        ["Ticket_182",          ["drop_column"]],
        ["Ticket_0",            ["drop_column"]],
    ]
}
